title: "GoFract - Fractal Explorer"
remote_theme: benc-uk/theme-msdark
#favicon: /vue/public/favicon.png
plugins:
  - jemoji
buttons:
  - b1:
    text: Gallery
    href: "https://code.benco.io/gofract/img/"
  - b2:
    text: Web Version
    href: "https://code.benco.io/gofract/web/"
